---
name: Unit Tests

defaults:
    run:
        shell: bash

on:
    push:
    pull_request:

jobs:
    prettier:
        name: Execute Unit Tests
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install Dependencies and Build
              run: npm ci --ignore-scripts && npm run build
            - name: Unit Tests
              run: npm run test
